### ISSUE TITLE
Force feedback vanish

### ISSUE THREAD

**Issue by Naveenkumarar** [kuriatsu/ros-g29-force-feedback#12]
The force feedback is vanish after 70 sec when I try to upload the torque from the calcCenteringForce() function.
force feedback supported is fine and all init work well. first 70 sec the force feedback works very well after that it vanish all of the sudden.

**Comment by kuriatsu** [comment]
OK, I will check.

**Comment by kuriatsu** [comment]
You are just using the ros node and don't use the example code, right?

**Comment by Naveenkumarar** [comment]
I am using example code. And it can upload effort for first 70 seconds only

**Comment by kuriatsu** [comment]
python's one?

**Comment by Naveenkumarar** [comment]
Cpp

**Comment by kuriatsu** [comment]
You may need to upload it continuously. (e.g., 1 time in 1 sec)
1 upload doesn't last long.

**Comment by Naveenkumarar** [comment]
I am uploading in infinite loop.

**Comment by kuriatsu** [comment]
You need to set `config/g29.yaml/auto_centering` to `false` if you want to control the wheel angle.
If it's true, you cannot publish /ff_target topic.

**Comment by kuriatsu** [comment]
I couldn't reproduce it. In my environment, ff works well without stopping.
Please show me what you are doing in more detail.

**Comment by Naveenkumarar** [comment]
I am using this code in nvidia jetson and using [G29 joystick](https://www.logitechg.com/en-us/products/driving/driving-force-racing-wheel.html). After 67 seconds the feedback vanish as I mention before.

I tried uploading force using the python evdev package, in python it worked very well.

So I tried to upload force in cpp without ros using following code:

`#include <sys/ioctl.h>
#include <unistd.h>
#include <fcntl.h>
#include <math.h>
#include <linux/input.h>
#include <stdio.h>
#include<iostream>
#include <unistd.h>
#include<cstring>

int m_device_handle;
struct ff_effect m_effect;
int m_axis_code = ABS_X;
    int m_axis_min;
    int m_axis_max;
std::string m_device_name="/dev/input/event3";

int testBit(int bit, unsigned char *array) {

    return ((array[bit / (sizeof(unsigned char) * 8)] >> (bit % (sizeof(unsigned char) * 8))) & 1);
}

void initDevice() {
    // setup device
    unsigned char key_bits[1+KEY_MAX/8/sizeof(unsigned char)];
    unsigned char abs_bits[1+ABS_MAX/8/sizeof(unsigned char)];
    unsigned char ff_bits[1+FF_MAX/8/sizeof(unsigned char)];
    struct input_event event;
    struct input_absinfo abs_info;

    m_device_handle = open(m_device_name.c_str(), O_RDWR|O_NONBLOCK);
    if (m_device_handle < 0) {
        std::cout << "ERROR: cannot open device : "<< m_device_name << std::endl;
        exit(1);

    } else {
        std::cout << "device opened" << std::endl;
        }

    // which axes has the device?
    memset(abs_bits, 0, sizeof(abs_bits));
    if (ioctl(m_device_handle, EVIOCGBIT(EV_ABS, sizeof(abs_bits)), abs_bits) < 0) {
        std::cout << "ERROR: cannot get abs bits" << std::endl;
        exit(1);
    }

    // get some information about force feedback
    memset(ff_bits, 0, sizeof(ff_bits));
    if (ioctl(m_device_handle, EVIOCGBIT(EV_FF, sizeof(ff_bits)), ff_bits) < 0) {
        std::cout << "ERROR: cannot get ff bits" << std::endl;
        exit(1);
    }

    // get axis value range
    if (ioctl(m_device_handle, EVIOCGABS(m_axis_code), &abs_info) < 0) {
        std::cout << "ERROR: cannot get axis range" << std::endl;
        exit(1);
    }
    m_axis_max = abs_info.maximum;
    m_axis_min = abs_info.minimum;
    if (m_axis_min >= m_axis_max) {
        std::cout << "ERROR: axis range has bad value" << std::endl;
        exit(1);
    }

    // check force feedback is supported?
    if(!testBit(FF_CONSTANT, ff_bits)) {
        std::cout << "ERROR: force feedback is not supported" << std::endl;
        exit(1);

    } else { 
        std::cout << "force feedback supported" << std::endl; 
        }

    // auto centering off
    memset(&event, 0, sizeof(event));
    event.type = EV_FF;
    event.code = FF_AUTOCENTER;
    event.value = 0;
    if (write(m_device_handle, &event, sizeof(event)) != sizeof(event)) {
        std::cout << "failed to disable auto centering" << std::endl;
        exit(1);
    }

    // init effect and get effect id
    memset(&m_effect, 0, sizeof(m_effect));
    m_effect.type = FF_CONSTANT;
    m_effect.id = -1; // initial value
    m_effect.trigger.button = 0;
    m_effect.trigger.interval = 0;
    m_effect.replay.length = 0xffff;  // longest value
    m_effect.replay.delay = 0; // delay from write(...)
    m_effect.u.constant.level = 0;
    m_effect.direction = 0xC000;
    m_effect.u.constant.envelope.attack_length = 0;
    m_effect.u.constant.envelope.attack_level = 0;
    m_effect.u.constant.envelope.fade_length = 0;
    m_effect.u.constant.envelope.fade_level = 0;

    if (ioctl(m_device_handle, EVIOCSFF, &m_effect) < 0) {
        std::cout << "failed to upload m_effect" << std::endl;
        exit(1);
    }

    // start m_effect
    memset(&event, 0, sizeof(event));
    event.type = EV_FF;
    event.code = m_effect.id;
    event.value = 1;
    if (write(m_device_handle, &event, sizeof(event)) != sizeof(event)) {
        std::cout << "failed to start event" << std::endl;
        exit(1);
    }
}

void uploadForce(const double &torque,
                                   const double &attack_length) {

    std::cout << torque << std::endl;
    // set effect
    m_effect.u.constant.level = 0x7fff * torque;
    m_effect.direction = 0xC000;
    m_effect.u.constant.envelope.attack_level = 0; /* 0x7fff * force / 2 */
    m_effect.u.constant.envelope.attack_length = attack_length;
    m_effect.u.constant.envelope.fade_level = 0;
    m_effect.u.constant.envelope.fade_length = attack_length;

    // upload effect
    if (ioctl(m_device_handle, EVIOCSFF, &m_effect) < 0) {
        std::cout << "failed to upload effect" << std::endl;
        // cout<<"Not uploaded"<<endl;
    }
    else{
        std::cout << "Effect is uploaded with torque"<<m_effect.u.constant.level << std::endl;
    }
}

int main()
{
    initDevice();

while(1){
    uploadForce(0.2, 0);
    usleep(200000);
}
}`

In this code also the feedback vanishes.

**Comment by kuriatsu** [comment]
> I am using this code in nvidia jetson and using [G29 joystick](https://www.logitechg.com/en-us/products/driving/driving-force-racing-wheel.html). After 67 seconds the feedback vanished as I mentioned before.
Do you have an error message or log file?
If your implementation has also the same problem, this may not be due to ROS.

**Comment by kuriatsu** [comment]
Or I think USB connection or something related to the OS.

**Comment by Naveenkumarar** [comment]
If the issue with the USB connection, it should not work on python
as well as it can't vanish in exactly 67 seconds.

**Comment by Naveenkumarar** [comment]
May be OS, I am using Ubuntu 18.04

**Comment by kuriatsu** [comment]
> upload the torque from the calcCenteringForce() function.

this means that you are not using my program (ff_node),  right?
If so, use my source code.

**Comment by kuriatsu** [comment]
But I can say that 
```c
usleep(200000);
```
will not work.
You need to upload the data more frequently.

**Comment by Naveenkumarar** [comment]
I used ff_node program, and end up with same issue

**Comment by kuriatsu** [comment]
Let me see your launch file, yaml file, and `ros2 topic pub...` command.

**Comment by Naveenkumarar** [comment]
1. Launch file:
![Screenshot 2023-01-31 at 11 10 50 AM](https://user-images.githubusercontent.com/29993827/215816079-b33c20ee-6661-4da7-8af8-65e8862c3233.png)

2. xml file
![Screenshot 2023-01-31 at 11 09 42 AM](https://user-images.githubusercontent.com/29993827/215815706-826cd361-f37b-4f28-bc93-69cc9326a2fb.png)

3. yaml file
![Screenshot 2023-01-31 at 11 12 24 AM](https://user-images.githubusercontent.com/29993827/215816590-76c84c2b-661f-4358-9699-fefb482dbe70.png)

4. launch command:
`roslaunch g29_feedback g29_force_feedback`

5. Issue:
Feedback occur continuously until 67 second

**Comment by kuriatsu** [comment]
If you need auto centering, the yaml file should be
`auto_centering: True`.
Or you need to continuously publish ros message.

**Comment by kuriatsu** [comment]
OK, I will check it in my environment.
If you can get the log file (`.ros/log/xxx`), please share with me.

**Comment by Naveenkumarar** [comment]
[roslaunch][INFO] 2023-02-03 10:47:54,506: Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
[roslaunch][INFO] 2023-02-03 10:47:54,555: Done checking log file disk usage. Usage is <1GB.
[roslaunch][INFO] 2023-02-03 10:47:54,556: roslaunch starting with args ['/opt/ros/melodic/bin/roslaunch', 'g29_force_feedback', 'g29_feedback.launch']
[roslaunch][INFO] 2023-02-03 10:47:54,556: roslaunch env is {'ROS_DISTRO': 'melodic', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'ROS_IP': '192.168.50.201', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/opt/ros/melodic/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'HOME': '/home/raslab', 'CMAKE_PREFIX_PATH': '/home/raslab/catkin_ws/devel:/home/raslab/cvbridge_build_ws/install:/opt/ros/melodic', 'DISPLAY': ':0', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'ROS_LOG_FILENAME': '/home/raslab/.ros/log/1651ff9e-a3da-11ed-a0ae-3e56a9c9b4fd/roslaunch-ubuntu-9443.log', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SHLVL': '1', 'LD_LIBRARY_PATH': '/home/raslab/catkin_ws/devel/lib:/home/raslab/cvbridge_build_ws/install/lib:/opt/ros/melodic/lib:/usr/local/cuda-10.2/lib64', 'ROS_ETC_DIR': '/opt/ros/melodic/etc/ros', 'SUDO_USER': 'raslab', 'ROS_PYTHON_VERSION': '2', 'USERNAME': 'root', 'COLORTERM': 'truecolor', 'PYTHONPATH': '/home/raslab/cvbridge_build_ws/install/lib/python3/dist-packages:/home/raslab/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages', 'SUDO_UID': '1000', 'ROS_ROOT': '/opt/ros/melodic/share/ros', 'PKG_CONFIG_PATH': '/home/raslab/catkin_ws/devel/lib/pkgconfig:/home/raslab/cvbridge_build_ws/install/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig', 'ROS_PACKAGE_PATH': '/home/raslab/catkin_ws/src/ros-g29-force-feedback:/home/raslab/catkin_ws/src/global_launch:/home/raslab/catkin_ws/src/racing_simulator:/home/raslab/cvbridge_build_ws/install/share:/opt/ros/melodic/share', '_': '/opt/ros/melodic/bin/roslaunch', 'SUDO_COMMAND': '/bin/bash', 'SUDO_GID': '1000', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/raslab/catkin_ws/devel/share/common-lisp', 'PWD': '/home/raslab', 'ROS_MASTER_URI': 'http://192.168.50.22:11311', 'ROS_VERSION': '1', 'MAIL': '/var/mail/root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}
[roslaunch][INFO] 2023-02-03 10:47:54,556: starting in server mode
[roslaunch.parent][INFO] 2023-02-03 10:47:54,557: starting roslaunch parent run
[roslaunch][INFO] 2023-02-03 10:47:54,557: loading roscore config file /opt/ros/melodic/etc/ros/roscore.xml
[roslaunch][INFO] 2023-02-03 10:47:55,089: Added core node of type [rosout/rosout] in namespace [/]
[roslaunch.config][INFO] 2023-02-03 10:47:55,090: loading config file /home/raslab/catkin_ws/src/ros-g29-force-feedback/launch/g29_feedback.launch
[roslaunch][INFO] 2023-02-03 10:47:55,174: Added node of type [g29_force_feedback/g29_force_feedback_node] in namespace [/]
[roslaunch][INFO] 2023-02-03 10:47:55,174: ... selected machine [] for node of type [g29_force_feedback/g29_force_feedback_node]
[roslaunch.pmon][INFO] 2023-02-03 10:47:55,177: start_process_monitor: creating ProcessMonitor
[roslaunch.pmon][INFO] 2023-02-03 10:47:55,177: created process monitor <ProcessMonitor(ProcessMonitor-1, initial daemon)>
[roslaunch.pmon][INFO] 2023-02-03 10:47:55,178: start_process_monitor: ProcessMonitor started
[roslaunch.parent][INFO] 2023-02-03 10:47:55,179: starting parent XML-RPC server
[roslaunch.server][INFO] 2023-02-03 10:47:55,180: starting roslaunch XML-RPC server
[roslaunch.server][INFO] 2023-02-03 10:47:55,182: waiting for roslaunch XML-RPC server to initialize
[xmlrpc][INFO] 2023-02-03 10:47:55,182: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2023-02-03 10:47:55,183: Started XML-RPC server [http://192.168.50.201:33987/]
[xmlrpc][INFO] 2023-02-03 10:47:55,183: xml rpc node: starting XML-RPC server
[roslaunch][INFO] 2023-02-03 10:47:55,196: started roslaunch server http://192.168.50.201:33987/
[roslaunch.parent][INFO] 2023-02-03 10:47:55,197: ... parent XML-RPC server started
[roslaunch][INFO] 2023-02-03 10:47:55,198: master.is_running[http://192.168.50.22:11311]
[roslaunch][INFO] 2023-02-03 10:47:55,468: master.is_running[http://192.168.50.22:11311]
[roslaunch][INFO] 2023-02-03 10:47:55,859: ROS_MASTER_URI=http://192.168.50.22:11311
[roslaunch][INFO] 2023-02-03 10:47:56,244: setting /roslaunch/uris/host_192_168_50_201__33987' to http://192.168.50.201:33987/
[roslaunch][INFO] 2023-02-03 10:47:56,335: load_parameters starting ...
[roslaunch][INFO] 2023-02-03 10:47:56,601: ... load_parameters complete
[roslaunch][INFO] 2023-02-03 10:47:56,602: launch_nodes: launching local nodes ...
[roslaunch][INFO] 2023-02-03 10:47:56,603: ... preparing to launch node of type [g29_force_feedback/g29_force_feedback_node]
[roslaunch][INFO] 2023-02-03 10:47:56,603: create_node_process: package[g29_force_feedback] type[g29_force_feedback_node] machine[Machine(name[] env_loader[None] address[localhost] ssh_port[22] user[None] assignable[True] timeout[10.0])] master_uri[http://192.168.50.22:11311]
[roslaunch][INFO] 2023-02-03 10:47:56,604: process[g29_feedback-1]: env[{'ROS_DISTRO': 'melodic', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'ROS_IP': '192.168.50.201', 'LOGNAME': 'root', 'USER': 'root', 'PATH': '/opt/ros/melodic/bin:/usr/local/cuda-10.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'HOME': '/home/raslab', 'CMAKE_PREFIX_PATH': '/home/raslab/catkin_ws/devel:/home/raslab/cvbridge_build_ws/install:/opt/ros/melodic', 'ROS_LOG_FILENAME': '/home/raslab/.ros/log/1651ff9e-a3da-11ed-a0ae-3e56a9c9b4fd/roslaunch-ubuntu-9443.log', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'SHLVL': '1', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LD_LIBRARY_PATH': '/home/raslab/catkin_ws/devel/lib:/home/raslab/cvbridge_build_ws/install/lib:/opt/ros/melodic/lib:/usr/local/cuda-10.2/lib64', 'ROS_MASTER_URI': 'http://192.168.50.22:11311', 'SUDO_USER': 'raslab', 'ROS_PYTHON_VERSION': '2', 'USERNAME': 'root', 'ROS_VERSION': '1', 'PYTHONPATH': '/home/raslab/cvbridge_build_ws/install/lib/python3/dist-packages:/home/raslab/catkin_ws/devel/lib/python2.7/dist-packages:/opt/ros/melodic/lib/python2.7/dist-packages', 'SUDO_UID': '1000', 'ROS_ROOT': '/opt/ros/melodic/share/ros', 'PKG_CONFIG_PATH': '/home/raslab/catkin_ws/devel/lib/pkgconfig:/home/raslab/cvbridge_build_ws/install/lib/pkgconfig:/opt/ros/melodic/lib/pkgconfig', 'ROS_PACKAGE_PATH': '/home/raslab/catkin_ws/src/ros-g29-force-feedback:/home/raslab/catkin_ws/src/global_launch:/home/raslab/catkin_ws/src/racing_simulator:/home/raslab/cvbridge_build_ws/install/share:/opt/ros/melodic/share', '_': '/opt/ros/melodic/bin/roslaunch', 'SUDO_COMMAND': '/bin/bash', 'SUDO_GID': '1000', 'DISPLAY': ':0', 'ROSLISP_PACKAGE_DIRECTORIES': '/home/raslab/catkin_ws/devel/share/common-lisp', 'PWD': '/home/raslab', 'ROS_ETC_DIR': '/opt/ros/melodic/etc/ros', 'COLORTERM': 'truecolor', 'MAIL': '/var/mail/root', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}]
[roslaunch][INFO] 2023-02-03 10:47:56,706: process[g29_feedback-1]: args[[u'/home/raslab/catkin_ws/devel/lib/g29_force_feedback/g29_force_feedback_node', u'__name:=g29_feedback']]
[roslaunch][INFO] 2023-02-03 10:47:56,707: ... created process [g29_feedback-1]
[roslaunch.pmon][INFO] 2023-02-03 10:47:56,707: ProcessMonitor.register[g29_feedback-1]
[roslaunch.pmon][INFO] 2023-02-03 10:47:56,707: ProcessMonitor.register[g29_feedback-1] complete
[roslaunch][INFO] 2023-02-03 10:47:56,707: ... registered process [g29_feedback-1]
[roslaunch][INFO] 2023-02-03 10:47:56,707: process[g29_feedback-1]: starting os process
[roslaunch][INFO] 2023-02-03 10:47:56,708: process[g29_feedback-1]: start w/ args [[u'/home/raslab/catkin_ws/devel/lib/g29_force_feedback/g29_force_feedback_node', u'__name:=g29_feedback', u'__log:=/home/raslab/.ros/log/1651ff9e-a3da-11ed-a0ae-3e56a9c9b4fd/g29_feedback-1.log']]
[roslaunch][INFO] 2023-02-03 10:47:56,708: process[g29_feedback-1]: cwd will be [/home/raslab/.ros]
[roslaunch][INFO] 2023-02-03 10:47:56,730: process[g29_feedback-1]: started with pid [9454]
[roslaunch][INFO] 2023-02-03 10:47:56,730: ... successfully launched [g29_feedback-1]
[roslaunch][INFO] 2023-02-03 10:47:56,731: ... launch_nodes complete
[roslaunch.pmon][INFO] 2023-02-03 10:47:56,731: registrations completed <ProcessMonitor(ProcessMonitor-1, started daemon 547818131952)>
[roslaunch.parent][INFO] 2023-02-03 10:47:56,731: ... roslaunch parent running, waiting for process exit
[roslaunch][INFO] 2023-02-03 10:47:56,731: spin
[roslaunch.pmon][INFO] 2023-02-03 10:49:39,302: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, started daemon 547818131952)>
[roslaunch.pmon][INFO] 2023-02-03 10:49:39,401: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 547818131952)>
[roslaunch.pmon][INFO] 2023-02-03 10:49:39,402: ProcessMonitor._post_run <ProcessMonitor(ProcessMonitor-1, started daemon 547818131952)>: remaining procs are [<roslaunch.nodeprocess.LocalProcess object at 0x7f8c8916d0>]
[roslaunch.pmon][INFO] 2023-02-03 10:49:39,403: ProcessMonitor exit: killing g29_feedback-1
[roslaunch][INFO] 2023-02-03 10:49:39,403: [g29_feedback-1] killing on exit
[roslaunch][INFO] 2023-02-03 10:49:39,405: process[g29_feedback-1]: killing os process with pid[9454] pgid[9454]
[roslaunch][INFO] 2023-02-03 10:49:39,405: [g29_feedback-1] sending SIGINT to pgid [9454]
[roslaunch][INFO] 2023-02-03 10:49:39,406: [g29_feedback-1] sent SIGINT to pgid [9454]
[roslaunch][INFO] 2023-02-03 10:49:52,024: process[g29_feedback-1]: SIGINT killed with return value 0
[roslaunch.pmon][INFO] 2023-02-03 10:49:52,025: ProcessMonitor exit: cleaning up data structures and signals
[roslaunch.pmon][INFO] 2023-02-03 10:49:52,026: ProcessMonitor exit: pmon has shutdown
[roslaunch][INFO] 2023-02-03 10:49:52,038: process monitor is done spinning, initiating full shutdown
[roslaunch][INFO] 2023-02-03 10:49:52,038: runner.stop()
[roslaunch][INFO] 2023-02-03 10:49:52,039: shutting down processing monitor...
[roslaunch][INFO] 2023-02-03 10:49:52,039: shutting down processing monitor <ProcessMonitor(ProcessMonitor-1, stopped daemon 547818131952)>
[roslaunch.pmon][INFO] 2023-02-03 10:49:52,039: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 547818131952)>
[roslaunch][INFO] 2023-02-03 10:49:52,040: ... shutting down processing monitor complete
[roslaunch][INFO] 2023-02-03 10:49:52,040: done
[roslaunch.pmon][INFO] 2023-02-03 10:49:52,040: ProcessMonitor.shutdown <ProcessMonitor(ProcessMonitor-1, stopped daemon 547818131952)>
[rospy.core][INFO] 2023-02-03 10:49:52,041: signal_shutdown [atexit]

**Comment by kuriatsu** [comment]
hmm..
Nothing is happening.
