### ISSUE TITLE
How to connect with LGSVL?

### ISSUE THREAD

**Issue by ParjanyaY** [kuriatsu/ros-g29-force-feedback#14]
Hello @kuriatsu,
As mentioned in the title, how would we connect this Logitech G29 force feedback with LGSVL simulator? I have tried to install ROS2 bridge for LGSVL, but it is not working at all.
Thank you

**Comment by kuriatsu** [comment]
I have tried ROS1 bridge, but never tried ROS2 bridge.
I cannot support ros2 bridge if it's a matter of LGSVL developer.
If there are some problems in the connection between ros2 bridge and g29-force-feedback node, I can support you.

**Comment by ParjanyaY** [comment]
@kuriatsu,
Thank you for the fast reply. 
I have installed ros2 bridge according to LGSVL official documentation and tried to run it along with g29-force-feedback simultaneously. This connection was not working as they weren't detecting each other. Am I doing it wrong, and what should I do in this situation?
This was the link I used to install ros2 nodes in LGSVL and create a subscriber node:
https://www.svlsimulator.com/docs/tutorials/create-ros2-ad-stack/#running-ros2-lgsvl-bridge

**Comment by kuriatsu** [comment]
OK, I understood.
You need to create a new node that subscribes steering information from LGSVL via ros2 bridge (maybe `/simulator/control/command` as described in the URL you pasted) and publish the steering angle to /ff_target message.

**Comment by kuriatsu** [comment]
Maybe you just run this command and be able to connect g29_node with lgsvl.

**Comment by ParjanyaY** [comment]
Thank you very much! I will try this and check if it's working.

**Comment by ParjanyaY** [comment]
I ran this code and it gave me the following error:

> NameError: name 'TwistStamped' is not defined

What is causing this error?

**Comment by ParjanyaY** [comment]
Alright, so I used the following code:
```
import rclpy
from rclpy.node import Node
from ros_g29_force_feedback.msg import ForceFeedback
from geometry_msgs.msg import TwistStamped


class Lgsvl2G29Steering(Node):
    def __init__(self):
        super().__init__('lgsvl_to_g29_steering_node')

        self.sub_image = self.create_subscription(TwistStamped, '/simulator/control/command', self.callback)
        self.publisher = self.create_publisher(ForceFeedback,"/ff_target", 10)

    def callback(self, msg):
        out_msg = ForceFeedback()
        out_msg.header.stamp = self.get_clock().now().to_msg()
        
        steering_angle = msg.twist.angular.x
        out_msg.position = steering_angle
        out_msg.torque = 0.8
        self.publisher.publish(out_msg)

def main(args=None):
    rclpy.init(args=args)
    lgsvl_to_g29_steering = Lgsvl2G29Steering()
    rclpy.spin(lgsvl_to_g29_steering)


if __name__ == '__main__':
    main()
```

But I'm still getting the following error while running it:

> Traceback (most recent call last):
  File "lgsvl_control.py", line 30, in <module>
    main()
  File "lgsvl_control.py", line 25, in main
    lgsvl_to_g29_steering = Lgsvl2G29Steering()
  File "lgsvl_control.py", line 11, in __init__
    self.sub_image = self.create_subscription(TwistStamped, '/simulator/control/command', self.callback)
TypeError: create_subscription() missing 1 required positional argument: 'qos_profile'

What is this 'qos_profile' and how do I set it up?

**Comment by kuriatsu** [comment]
Sorry, 1 mistake at `create_subscription`
```python
import rclpy
from rclpy.node import Node
from ros_g29_force_feedback.msg import ForceFeedback


class Lgsvl2G29Steering(Node):
    def __init__(self):
        super().__init__('lgsvl_to_g29_steering_node')

        self.sub_image = self.create_subscription(TwistStamped, '/simulator/control/command', self.callback, 10)
        self.publisher = self.create_publisher(ForceFeedback,"/ff_target", 10)

    def callback(self, msg):
        out_msg = ForceFeedback()
        out_msg.header.stamp = self.get_clock().now().to_msg()
        
        steering_angle = msg.twist.angular.x
        out_msg.position = steering_angle
        out_msg.torque = 0.8
        self.publisher.publish(out_msg)

def main(args=None):
    rclpy.init(args=args)
    lgsvl_to_g29_steering = Lgsvl2G29Steering()
    rclpy.spin(lgsvl_to_g29_steering)


if __name__ == '__main__':
    main()
```
