### ISSUE TITLE
How to connect to Carla with ROS1

### ISSUE THREAD

**Issue by Yucong-Wang** [kuriatsu/ros-g29-force-feedback#16]
carla_control.py is used for ROS2. But I want to connect to Carla with ros1 because I use ubuntu. Could you please share me your code with ros1. Thank you very much ！

**Comment by kuriatsu** [comment]
Example code for ros1-carla connection was uploaded.
Please check https://github.com/kuriatsu/ros-g29-force-feedback/tree/ros1.
If you found some error, please notify me.
