### ISSUE TITLE
when I tried launch ros_g29_force_feedback

### ISSUE THREAD

**Issue by yaoweixiao-ux** [kuriatsu/ros-g29-force-feedback#17]
error info 
[ERROR] [rcl]:Failed to parse global arguments 
How can I deal with this problem?

**Comment by kuriatsu** [comment]
The Yaml file wasn't loaded correctly.
How did you run the node?

**Comment by yaoweixiao-ux** [comment]
~/Desktop/work_sp/Third_part/LG29$ ros2 run ros_g29_force_feedback g29_force_feedback --ros-args --params-file ros2_ws/src/ros_g29_force_feedback/config/g29.yaml 
[ERROR] [1677549815.870385879] [rcl]: Failed to parse global arguments
terminate called after throwing an instance of 'rclcpp::exceptions::RCLInvalidROSArgsError'
  what():  failed to initialize rcl: Couldn't parse params file: '--params-file ros2_ws/src/ros_g29_force_feedback/config/g29.yaml'. Error: Error opening YAML file, at /tmp/binarydeb/ros-galactic-rcl-yaml-param-parser-3.1.4/src/parser.c:270, at /tmp/binarydeb/ros-galactic-rcl-3.1.4/src/rcl/arguments.c:406

**Comment by yaoweixiao-ux** [comment]
Rebbot I have deal with this problem Thanks!!! good job

**Comment by kuriatsu** [comment]
OK, but how?
I couldn't reproduce this problem, actually.
