### ISSUE TITLE
ROS1 branch does not build properly due to errors

### ISSUE THREAD

**Issue by pedrohdsimoes** [kuriatsu/ros-g29-force-feedback#18]
I tried using the Ros1 branch to test it, but the g29_force_feedback.cpp had a few errors. I also think the package name did not matched because in one place was g29_steering_wheel and another was ros_g29_steering_wheel.

Also in the example code carla_control.py there is also a few mistakes that break the code like having __init__() with a client argument and also on timer_cb().

I also got another error in publishing with ros in that script because you have rospy.Publisher("/ff_target", ForceFeedback, 10) instead of rospy.Publisher("/ff_target", ForceFeedback, queue_size=10).

I fixed all of this and successfully used it and tested it.

I can create a pull request if you want to have a look

**Comment by kuriatsu** [comment]
Thanks a lot.
Actually, the ros1 branch was not tested well after the major fix.
Please create PR!
