### ISSUE TITLE
hi I want connect autoware.universe and g29 

### ISSUE THREAD

**Issue by yaoweixiao-ux** [kuriatsu/ros-g29-force-feedback#20]
I notice autoware.universe
subscribe /vehicle/status/steering_status
---
stamp:
  sec: 1679539267
  nanosec: 645533388
steering_tire_angle: -0.3019617795944214
---
g29-force-feedback
publish /ff_target ros_g29_force_feedback/msg/ForceFeedback "header: {stamp: {sec:0, nanosec:0}, frame_id: ' '}, position: 0.3, torque:0.5"
so I want let position=steering_tire_angle、but i don't know how to achieve it, Can you teach me how to do it 
my Email is 1009742794@qq.com 
Thanks you

**Comment by yaoweixiao-ux** [comment]
After check all project i think author must have do this job！
so I ask for help

**Comment by kuriatsu** [comment]
You need to write the ros2 node which acts like this

1. subscribing vehicle status message
2. position=steering_tire_angle
3. publish the ForceFeedback message.

You may have done by manually, right?
So just write down the process to the code.

**Comment by yaoweixiao-ux** [comment]
how can i conversion with you？ i meet some trouble

**Comment by yaoweixiao-ux** [comment]
cmake_minimum_required(VERSION 3.8)
project(voyager_pub_sub)


# Default to C99
if(NOT CMAKE_C_STANDARD)
  set(CMAKE_C_STANDARD 99)
endif()

# Default to C++14
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(rosidl_default_generators REQUIRED)
find_package(autoware_auto_vehicle_msgs REQUIRED)
find_package(ros_g29_force_feedback REQUIRED)

set(dependencies
  rclcpp
  std_msgs
  autoware_auto_vehicle_msgs
  ros_g29_force_feedback
)

# Generate project targer with msg
rosidl_generate_interfaces(${PROJECT_NAME}
  "msg/ForceFeedback.msg"
  DEPENDENCIES rosidl_default_generators std_msgs)

# Add executable
add_executable(voyager_node src/voyager.cpp)
ament_target_dependencies(voyager_node ${dependencies})


ament_export_dependencies(rosidl_default_runtime)

if(BUILD_TESTING)
  find_package(ament_lint_auto REQUIRED)
  # the following line skips the linter which checks for copyrights
  # uncomment the line when a copyright and license is not present in all source files
  #set(ament_cmake_copyright_FOUND TRUE)
  # the following line skips cpplint (only works in a git repo)
  # uncomment the line when this package is not in a git repo
  #set(ament_cmake_cpplint_FOUND TRUE)
  ament_lint_auto_find_test_dependencies()
endif()

ament_package()

**Comment by yaoweixiao-ux** [comment]
<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>voyager_pub_sub</name>
  <version>0.0.0</version>
  <description>TODO: Package description</description>
  <maintainer email="m0_48707860@example.com">voyager</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rosidl_default_generators</build_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>
  <member_of_group>rosidl_interface_packages</member_of_group>

  <depend>std_msgs</depend>
  <depend>rclcpp</depend>
  <depend>autoware_auto_vehicle_msgs</depend>
  <depend>ros_g29_force_feedback</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
``

**Comment by yaoweixiao-ux** [comment]
colcon build pass!  can you help me check I have some problem?

**Comment by kuriatsu** [comment]
Good job!
Please test it. If there are some problems, I can help you.

**Comment by yaoweixiao-ux** [comment]
moring

**Comment by yaoweixiao-ux** [comment]
``rriding autoware_auto_vehicle_msgs
Starting >>> autoware_auto_vehicle_msgs
Finished <<< autoware_auto_vehicle_msgs [3.52s]                     
Starting >>> voyager_pub_sub
--- stderr: voyager_pub_sub                             
In file included from /usr/include/x86_64-linux-gnu/c++/9/bits/c++allocator.h:33,
                 from /usr/include/c++/9/bits/allocator.h:46,
                 from /usr/include/c++/9/memory:63,
                 from /opt/ros/galactic/include/rclcpp/rclcpp.hpp:154,
                 from /home/voyager/Desktop/voyager_1/ros2_ws/voyager_pub_sub/src/voyager.cpp:1:
/usr/include/c++/9/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = GreateBusinessNode; _Args = {const char (&)[8]}; _Tp = GreateBusinessNode]’:
/usr/include/c++/9/bits/alloc_traits.h:483:4:   required from ‘static void std::allocator_traits<std::allocator<_Tp1> >::construct(std::allocator_traits<std::allocator<_Tp1> >::allocator_type&, _Up*, _Args&& ...) [with _Up = GreateBusinessNode; _Args = {const char (&)[8]}; _Tp = GreateBusinessNode; std::allocator_traits<std::allocator<_Tp1> >::allocator_type = std::allocator<GreateBusinessNode>]’
/usr/include/c++/9/bits/shared_ptr_base.h:548:39:   required from ‘std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_Sp_counted_ptr_inplace(_Alloc, _Args&& ...) [with _Args = {const char (&)[8]}; _Tp = GreateBusinessNode; _Alloc = std::allocator<GreateBusinessNode>; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr_base.h:679:16:   required from ‘std::__shared_count<_Lp>::__shared_count(_Tp*&, std::_Sp_alloc_shared_tag<_Alloc>, _Args&& ...) [with _Tp = GreateBusinessNode; _Alloc = std::allocator<GreateBusinessNode>; _Args = {const char (&)[8]}; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr_base.h:1344:71:   required from ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<GreateBusinessNode>; _Args = {const char (&)[8]}; _Tp = GreateBusinessNode; __gnu_cxx::_Lock_policy _Lp = __gnu_cxx::_S_atomic]’
/usr/include/c++/9/bits/shared_ptr.h:359:59:   required from ‘std::shared_ptr<_Tp>::shared_ptr(std::_Sp_alloc_shared_tag<_Tp>, _Args&& ...) [with _Alloc = std::allocator<GreateBusinessNode>; _Args = {const char (&)[8]}; _Tp = GreateBusinessNode]’
/usr/include/c++/9/bits/shared_ptr.h:701:14:   required from ‘std::shared_ptr<_Tp> std::allocate_shared(const _Alloc&, _Args&& ...) [with _Tp = GreateBusinessNode; _Alloc = std::allocator<GreateBusinessNode>; _Args = {const char (&)[8]}]’
/usr/include/c++/9/bits/shared_ptr.h:717:39:   required from ‘std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = GreateBusinessNode; _Args = {const char (&)[8]}]’
/home/voyager/Desktop/voyager_1/ros2_ws/voyager_pub_sub/src/voyager.cpp:37:61:   required from here
/usr/include/c++/9/ext/new_allocator.h:146:4: error: no matching function for call to ‘GreateBusinessNode::GreateBusinessNode(const char [8])’
  146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/voyager/Desktop/voyager_1/ros2_ws/voyager_pub_sub/src/voyager.cpp:10:3: note: candidate: ‘GreateBusinessNode::GreateBusinessNode()’
   10 |   GreateBusinessNode()
      |   ^~~~~~~~~~~~~~~~~~
/home/voyager/Desktop/voyager_1/ros2_ws/voyager_pub_sub/src/voyager.cpp:10:3: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [CMakeFiles/voyager_node.dir/build.make:63：CMakeFiles/voyager_node.dir/src/voyager.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:123：CMakeFiles/voyager_node.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
---
Failed   <<< voyager_pub_sub [2.36s, exited with code 2]

**Comment by yaoweixiao-ux** [comment]
Can you help  me deal with this issus

**Comment by kuriatsu** [comment]
No constructor in your code.

**Comment by kuriatsu** [comment]
auto node = std::make_shared();
↓
auto node = std::make_shared<GreateBusinessNode>();

**Comment by yaoweixiao-ux** [comment]
thank you I have finish this job
