### ISSUE TITLE
Hi I want to know how to record G29 topic info

### ISSUE THREAD

**Issue by yaoweixiao-ux** [kuriatsu/ros-g29-force-feedback#21]
ros2 bag record which topic

**Comment by kuriatsu** [comment]
https://index.ros.org/p/joy/

**Comment by yaoweixiao-ux** [comment]
Do you means I need this ros bag dependence, than I just need ros2 bag record joy/set_feedback  right?

**Comment by kuriatsu** [comment]
I thought you wanted to record the wheel state.
If so, you can use the joy package.
But anyway, `/ff_target` topic is used for rotating the wheel in this package.

**Comment by yaoweixiao-ux** [comment]
device opened
ERROR: force feedback is not supported
when I launch the topic I meet this problem

**Comment by yaoweixiao-ux** [comment]
I cannot read the data on the pedals and steering wheel using stest-gtk on Ubuntu

**Comment by kuriatsu** [comment]
Please check this requirement
https://github.com/kuriatsu/ros-g29-force-feedback#requirement
and tweak the configuration file.

**Comment by yaoweixiao-ux** [comment]
I followed your step,and still have this problem

**Comment by yaoweixiao-ux** [comment]
voyager@voyager-Legion-Y7000P-IAH7:~/Desktop/Lg29$ cat /boot/config-5.15.0-67-generic | grep CONFIG_LOGIWHEELS_FF
CONFIG_LOGIWHEELS_FF=y

**Comment by kuriatsu** [comment]
Did you change `device_name` in g29.yaml?

**Comment by yaoweixiao-ux** [comment]
> I thought you wanted to record the wheel state. If so, you can use the joy package. But anyway, `/ff_target` topic is used for rotating the wheel in this package.

you means I need add joy bag in your project,and record this topic?

**Comment by yaoweixiao-ux** [comment]
Do i need to change your code?

**Comment by kuriatsu** [comment]
Sorry, I don't understand what you want to do.
If you are struggling to rotate the wheel, please follow the instructions. https://github.com/kuriatsu/ros-g29-force-feedback/blob/master/README.md#usage

**Comment by yaoweixiao-ux** [comment]
I want to manually record the rotation of the steering wheel and play it back in the form of a ROS package. The previous issue was that my steering wheel was damaged by someone else, and I replaced it with a new one and repaired it

**Comment by yaoweixiao-ux** [comment]
Just record the information and play it out again
