### ISSUE TITLE
Unable to change device name in config file

### ISSUE THREAD

**Issue by ziamfarhan** [kuriatsu/ros-g29-force-feedback#23]
I have ros melodic installed on my Ubuntu 18. I've followed all the instructions for the installation for ros1 and everything seemed to go smoothly. However even after changing the device name in the config file to let's say /dev/input/event9, I still get the following when doing rosrun 
```
ERROR: cannot open device : /dev/input/event14
``` 
I've tried deleting and creating the workspace multiple times, ensured the config file is saved yet it still gives the same error. Can someone help with this?

**Comment by kuriatsu** [comment]
Same as the email. Please check!

**Comment by ziamfarhan** [comment]
The output I got for for cat /proc/bus/input/devices

![20230511_142852](https://github.com/kuriatsu/ros-g29-force-feedback/assets/81572887/8ae02477-4595-4087-b1fc-3d8f3c1da45d)

**Comment by ziamfarhan** [comment]
Using rosparam to set the config did do the trick, and when node is activated, I can feel a force. But when publishing a message using rostopic pub, nothing really happens. Also when testing with fftest, I do notice a constant force, but none of the other tests worked

**Comment by kuriatsu** [comment]
What command did you use?
Please paste ros2 run and ros2 pub command what you used.
g29.yaml too.

**Comment by ziamfarhan** [comment]
We finally got it to work on ros2! Unfortunately in ros1 for some reason rostopic pub did not seem to do anything. Anyway, many thanks!

**Comment by ziamfarhan** [comment]
One last question, to test this with Carla, do we just simply install Carla and run the example? Or are there several other steps for the step we should be vary of. We are using an Ubuntu 20

**Comment by kuriatsu** [comment]
No other steps are required.
Just run the carla, g29 node, put ego_vehicle or hero in carla, and everything will work.
But take care, you cannot control the vehicle by g29.
To do that, you need to implement such node or functions.
