### ISSUE TITLE
Wrong type conversion to `m_loop_rate` which make it dosen't work

### ISSUE THREAD

**Issue by XZHSTAX** [kuriatsu/ros-g29-force-feedback#30]
In your code
https://github.com/kuriatsu/ros-g29-force-feedback/blob/1b7b30ad6eae52ee999cbf0aa0a26ff0a7f58059/src/g29_force_feedback.cpp#L92
Since the cast operator has a higher precedence than the multiplication operator, the `int` cast will be applied to `m_loop_rate` rather than `m_loop_rate*1000`. If `m_loop_rate<1` , then `(int)m_loop_rate*1000=0`, which causes the timer to invoke the `loop ` function as fast as possible instead of the desired rate.

The code should be modified as follows:
```c++
timer = this->create_wall_timer(std::chrono::milliseconds((int)(m_loop_rate*1000)), 
            std::bind(&G29ForceFeedback::loop,this));
```
This issue may not have a significant impact on the final outcome, and you can choose to ignore it. However, if you decide to make modifications, it is recommended to also update the `loop_rate` in g29.yaml to 0.001.(My computer can read information from the G29 steering wheel approximately every 0.002 seconds, so I recommend setting the loop_rate to 0.001 in g29.yaml.)

Thank you for you and your code. I have learned a lot, and I wish you all the best！

**Comment by kuriatsu** [comment]
Thank you for pointing out this potential bug!
For sure it needs to be fixed.
I will merge your PR if you can, or  I just fix the portion by myself.
