### ISSUE TITLE
ERROR: force feedback is not supported

### ISSUE THREAD

**Issue by kmeeey** [kuriatsu/ros-g29-force-feedback#32]
hello.

My system environment is Ubuntu 20.04, and my ROS 2 version is Foxy. I checked that my kernel supports force feedback as follows:
nc@nc:~/ros2_ws$ cat /boot/config-5.15.0-105-generic | grep CONFIG_LOGIWHEELS_FF
CONFIG_LOGIWHEELS_FF=y

But when I run [ros2 launch ros_g29_force_feedback g29_feedback.launch.py], I get the following results:

[INFO] [launch]: Default logging verbosity is set to INFO
--> Found handler at /dev/input/event5
[INFO] [g29_force_feedback-1]: process started with pid [5845]
[g29_force_feedback-1] Opening device : /dev/input/event5
[g29_force_feedback-1] device opened
[g29_force_feedback-1] FF_CONSTANT : 82
[g29_force_feedback-1] ERROR: force feedback is not supported
[ERROR] [g29_force_feedback-1]: process has died [pid 5845, exit code 1, cmd '/home/nc/ros2_ws/install/ros_g29_force_feedback/lib/ros_g29_force_feedback/g29_force_feedback --ros-args -r __node:=g29_force_feedback -r __ns:=/ --params-file /home/nc/ros2_ws/install/ros_g29_force_feedback/share/ros_g29_force_feedback/config/g29.yaml --params-file /tmp/launch_params_8fsyn5sx'].

How can I solve this problem? Looking forward to your reply.

**Comment by kmeeey** [comment]
I know what you mean.
But the content of launch is：
`def find_handlers():
    stream = os.popen("cat /proc/bus/input/devices")
    stream = stream.read().split('\n')
    found_name = False
    for line in stream:
        if('N: Name="Logitech G923 Racing Wheel for PlayStation 4 and PC"' in line or found_name):
            if(not found_name):
                idx = stream.index(line)
            else:
                idx = idx+1
            #print(f"{idx}: {line}")
            found_name = True
            if(line == ""):
                found_name = False
            if("H: Handlers" in line):
                handlers = line.split("=")[1].split(" ")
                for h in handlers:
                    if h.startswith("event"):
                        print("--> Found handler at /dev/input/"+h)
                        return(h)`
I checked that the number is correct.

**Comment by kmeeey** [comment]
I know what you mean.
But the content of launch is：
`def find_handlers():
    stream = os.popen("cat /proc/bus/input/devices")
    stream = stream.read().split('\n')
    found_name = False
    for line in stream:
        if('N: Name="Logitech G923 Racing Wheel for PlayStation 4 and PC"' in line or found_name):
            if(not found_name):
                idx = stream.index(line)
            else:
                idx = idx+1
            #print(f"{idx}: {line}")
            found_name = True
            if(line == ""):
                found_name = False
            if("H: Handlers" in line):
                handlers = line.split("=")[1].split(" ")
                for h in handlers:
                    if h.startswith("event"):
                        print("--> Found handler at /dev/input/"+h)
                        return(h)`
I checked that the number is correct.

**Comment by kuriatsu** [comment]
Could you comment-out these lines?
This checking script doesn't work for g923 for some reason. 
https://github.com/kuriatsu/ros-g29-force-feedback/blob/9ad58d33d75a0fc80998d53f364d65f96fca9b45/src/g29_force_feedback.cpp#L255-L260

**Comment by kmeeey** [comment]
Thank you for receiving your reply！
I tried the g923 and the g29.The g29 also has this problem.
When I use g923, and comment those lines you said,The results are as follows:
`[INFO] [launch]: All log files can be found below /home/nc/.ros/log/2024-05-07-12-30-29-292180-nc-23591
[INFO] [launch]: Default logging verbosity is set to INFO
--> Found handler at /dev/input/event17
[INFO] [g29_force_feedback-1]: process started with pid [23625]
[g29_force_feedback-1] Opening device : /dev/input/event17
[g29_force_feedback-1] device opened
[g29_force_feedback-1] FF_CONSTANT : 82
[g29_force_feedback-1] failed to upload m_effect
[ERROR] [g29_force_feedback-1]: process has died [pid 23625, exit code 1, cmd '/home/nc/ros2_ws/install/ros_g29_force_feedback/lib/ros_g29_force_feedback/g29_force_feedback --ros-args -r __node:=g29_force_feedback -r __ns:=/ --params-file /home/nc/ros2_ws/install/ros_g29_force_feedback/share/ros_g29_force_feedback/config/g29.yaml --params-file /tmp/launch_params_0gwcwn7m'].`
I'm sorry to trouble you, but I'd like to solve this problem.

**Comment by kmeeey** [comment]
Thank you for receiving your reply！
I tried the g923 and the g29.The g29 also has this problem.
When I use g923, and comment those lines you said,The results are as follows:
`[INFO] [launch]: All log files can be found below /home/nc/.ros/log/2024-05-07-12-30-29-292180-nc-23591
[INFO] [launch]: Default logging verbosity is set to INFO
--> Found handler at /dev/input/event17
[INFO] [g29_force_feedback-1]: process started with pid [23625]
[g29_force_feedback-1] Opening device : /dev/input/event17
[g29_force_feedback-1] device opened
[g29_force_feedback-1] FF_CONSTANT : 82
[g29_force_feedback-1] failed to upload m_effect
[ERROR] [g29_force_feedback-1]: process has died [pid 23625, exit code 1, cmd '/home/nc/ros2_ws/install/ros_g29_force_feedback/lib/ros_g29_force_feedback/g29_force_feedback --ros-args -r __node:=g29_force_feedback -r __ns:=/ --params-file /home/nc/ros2_ws/install/ros_g29_force_feedback/share/ros_g29_force_feedback/config/g29.yaml --params-file /tmp/launch_params_0gwcwn7m'].`
I'm sorry to trouble you, but I'd like to solve this problem.

**Comment by kmeeey** [comment]
Thank you for receiving your reply！
I tried the g923 and the g29.The g29 also has this problem.
When I use g923, and comment those lines you said,The results are as follows:
[INFO] [launch]: All log files can be found below /home/nc/.ros/log/2024-05-07-12-30-29-292180-nc-23591
[INFO] [launch]: Default logging verbosity is set to INFO
--> Found handler at /dev/input/event17
[INFO] [g29_force_feedback-1]: process started with pid [23625]
[g29_force_feedback-1] Opening device : /dev/input/event17
[g29_force_feedback-1] device opened
[g29_force_feedback-1] FF_CONSTANT : 82
[g29_force_feedback-1] failed to upload m_effect
[ERROR] [g29_force_feedback-1]: process has died [pid 23625, exit code 1, cmd '/home/nc/ros2_ws/install/ros_g29_force_feedback/lib/ros_g29_force_feedback/g29_force_feedback --ros-args -r __node:=g29_force_feedback -r __ns:=/ --params-file /home/nc/ros2_ws/install/ros_g29_force_feedback/share/ros_g29_force_feedback/config/g29.yaml --params-file /tmp/launch_params_0gwcwn7m'].
I'm sorry to trouble you, but I'd like to solve this problem.

**Comment by kmeeey** [comment]
I get this log:

Force feedback test program.
HOLD FIRMLY YOUR WHEEL OR JOYSTICK TO PREVENT DAMAGES

Device /dev/input/event5 opened
Features:
  * Absolute axes: X, Y, Z, RX, RY, RZ, Hat 0 X, Hat 0 Y, 
    [3F 00 03 00 00 00 00 00 ]
  * Relative axes: 
    [00 00 ]
  * Force feedback effects types: 
    Force feedback periodic effects: 
    [00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ]
  * Number of simultaneous effects: 0

Uploading effect #0 (Periodic sinusoidal) ... Error:: Function not implemented
Uploading effect #1 (Constant) ... Error: Function not implemented
Uploading effect #2 (Spring) ... Error: Function not implemented
Uploading effect #3 (Damper) ... Error: Function not implemented
Uploading effect #4 (Strong rumble, with heavy motor) ... Error: Function not implemented
Uploading effect #5 (Weak rumble, with light motor) ... Error: Function not implemented
Enter effect number, -1 to exit
5
Now Playing: Weak Rumble

I think there's something wrong with my g29.

**Comment by kuriatsu** [comment]
I think so too. 
When you plug in the wheel, does it turn right and left for calibration?
I'm not sure why it doesn't work.
```bash
$ cat /proc/bus/input/devices
```
may show 2 lines of G29 or G923.
If so, each line has a different event number and either of them doesn't work.
Worth checking again.
