### ISSUE TITLE
What is License. MIT? Apache 2? 

### ISSUE THREAD

**Issue by yukkysaito** [kuriatsu/ros-g29-force-feedback#34]
The package license here is MIT, but the license file is Apache2. Which is correct?
- https://github.com/kuriatsu/ros-g29-force-feedback/blob/master/package.xml#L8
- https://github.com/kuriatsu/ros-g29-force-feedback/blob/master/LICENSE

**Comment by kuriatsu** [comment]
Apache2 is correct.

**Comment by yukkysaito** [comment]
Ok :+1: 
https://github.com/kuriatsu/ros-g29-force-feedback/pull/35

**Comment by kuriatsu** [comment]
Thank you so much!
