### ISSUE TITLE
The pakage 's example has typos

### ISSUE THREAD

**Issue by ncnynl** [kuriatsu/ros-g29-force-feedback#5]
rostopic pub /ff_target g29-force-feedback/ForceFeedback "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
angle: 0.3
force: 0.0
pid_mode: true"

This example has typos, it should be

rostopic pub /ff_target g29_force_feedback/ForceFeedback "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
angle: 0.3
force: 0.0
pid_mode: true"

**Comment by kuriatsu** [comment]
Thanks.
Please create pull request it if you have time. Then I will merge it.
