### ISSUE TITLE
wheel turns left and right in PID mode 

### ISSUE THREAD

**Issue by siddharthcb** [kuriatsu/ros-g29-force-feedback#7]
Thanks for this helpful package.
I am facing an issue with the steering wheel not coming to the state of total rest when no angle is given... it comes to center but keep oscillating left and right.
I tried playing with the PID values but it did not help and increasing the offset does not help either.
Is there  a way i can solve this?

**Comment by kuriatsu** [comment]
Yes, this dead zone is a serious problem.
I gonna try to find the cause in this month.

**Comment by kuriatsu** [comment]
Please try https://github.com/kuriatsu/ros-g29-force-feedback/tree/fix/oscillation branch.

**Comment by kuriatsu** [comment]
PID mode removed, but oscillation solved.

**Comment by kuriatsu** [comment]
@siddharthcb Please try the current master branch.
The problem almost solved.

**Comment by siddharthcb** [comment]
thank you, will try it sometime and update you
