### ISSUE TITLE
About carla connection

### ISSUE THREAD

**Issue by VincentCheung991214** [kuriatsu/ros-g29-force-feedback#8]
I am quite new sorry, but how to connect with my Carla Server for manual control?

**Comment by kuriatsu** [comment]
You need to make a node that gets ego_vehicle's control_cmd using PythonAPI and publish the wheel angle to this custom msg.

**Comment by kuriatsu** [comment]
And I added the test code to sync the vehicle in the carla (rolename="hero" or "ego_vehicle").
Try `python3 examples/carla_control.py`
